### ISSUE TITLE
docker 镜像启动错误

### ISSUE THREAD

**Issue by jabezGit** [longfeizheng/logback#1]
你好，我在启动docker文件时候，出现了如下错误：
这个问题看似是docker镜像自身的问题，望解决下呗

`Deploying '<unknown> Dockerfile: Dockerfile'...
Building image...
Step 1/5 : FROM hub.c.163.com/wuxukun/maven-aliyun:3-jdk-8

 ---> 676639454cb4

Step 2/5 : ADD ./target/spring-boot.jar /app.jar

Error: ResponseItem.ErrorDetail[code=<null>,message=ADD failed: stat /var/lib/docker/tmp/docker-builder379459939/target/spring-boot.jar: no such file or directory]
Failed to deploy '<unknown> Dockerfile: Dockerfile': ADD failed: stat /var/lib/docker/tmp/docker-builder379459939/target/spring-boot.jar: no such file or directory`

**Comment by longfeizheng** [comment]
不好意思，看项目名字也看出来了，没想到后期往里面添加了这么多东西，一直没来的及修改

**Comment by jabezGit** [comment]
我对这个项目也不是很了解哈，这个docker是不是一个redis的服务，我用自己的redis的docker也是可以的吗？

**Comment by longfeizheng** [comment]
是的，数据库和redis的地址配置为本地**IP**地址，不要配置成`127.0.0.1`

**Comment by jabezGit** [comment]
嗯嗯，我使用了一个自己的redis服务器就正常的启动了，项目也启动起来了
需要修改redis 的端口一致就可以了

**Comment by longfeizheng** [comment]
现在可以使用docker-compose 启动项目
