### ISSUE TITLE
微信登录的redirect_uri可以通过配置改变吗？

### ISSUE THREAD

**Issue by TonyLuo** [longfeizheng/logback#2]
在本地测试的时候redirect_uri=localhost, 微信跳转页面报redirect_uri 参数错误，能否通过改变默认的redirect_uri？

**Comment by longfeizheng** [comment]
使用社交登录需要配置host，微信的appid是从淘宝购买已经过期。qq和微博可以使用，host配置：127.0.0.1 www.merryyou.cn

**Comment by longfeizheng** [comment]
社交登录需要通过域名访问，www.merryyou.cn(所以需要配置host文件)因为回调地址是`http://www.merryyou.cn/login/qq;http://www.merryyou.cn/connect/qq`
