### ISSUE TITLE
sessionManagement中的maximumSessions不生效

### ISSUE THREAD

**Issue by midKingKing** [longfeizheng/logback#4]
您好，我最近在看您的这系列Blog学习spirng-security的相关知识，但是现在发现sessionMannager设置的maximumSessions不生效，是否是因为redisession的原因，请问您有碰到这个问题么，求解答，谢谢

**Comment by longfeizheng** [comment]
复写User 类的 ``hashCode()`和 `equals()`方法试下，
`    @Override
    public int hashCode() {
        return username.hashCode();
    }

    @Override
    public boolean equals(Object rhs) {
        if (rhs instanceof SysUser) {
            return username.equals(((SysUser) rhs).username);
        }
        return false;
    }`
